name: matrix-build
on: push

jobs:
  job:
    name: build-project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: checkout project
        uses: actions/checkout@v2

      - name: generate prooject
        run: cmake . -B.build_release -DCMAKE_BUILD_TYPE=Release

      - name: build project
        run: cmake --build .build_release --config Release