name: matrix-build
on: push

jobs:
  job:
    name: build-project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      build_dir: '${{ github.workspace }}/build/'
    strategy: 
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx
    steps:
      - name: install cmake
        uses: lukka/get-cmake@latest

      - name: checkout project
        uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/external/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ env.build_dir }}/vcpkg_installed


          