name: static analysis

on: [pull_request]

jobs:
  graph:
    runs-on: ubuntu-latest
    steps:
    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        exclude_dir: dependencies